//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.16 at 07:08:00 PM CET 
//


package it.polito.dp2.RNS.sol3.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vehicleUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="authToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="positionUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="stateUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element ref="{}placesIdPath"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vehicleUri",
    "authToken",
    "positionUri",
    "stateUri",
    "placesIdPath"
})
@XmlRootElement(name = "addVehicleResponse")
public class AddVehicleResponse {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String vehicleUri;
    @XmlElement(required = true)
    protected String authToken;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String positionUri;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String stateUri;
    @XmlElement(required = true)
    protected PlacesIdPath placesIdPath;

    /**
     * Gets the value of the vehicleUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleUri() {
        return vehicleUri;
    }

    /**
     * Sets the value of the vehicleUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleUri(String value) {
        this.vehicleUri = value;
    }

    /**
     * Gets the value of the authToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthToken() {
        return authToken;
    }

    /**
     * Sets the value of the authToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthToken(String value) {
        this.authToken = value;
    }

    /**
     * Gets the value of the positionUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionUri() {
        return positionUri;
    }

    /**
     * Sets the value of the positionUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionUri(String value) {
        this.positionUri = value;
    }

    /**
     * Gets the value of the stateUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateUri() {
        return stateUri;
    }

    /**
     * Sets the value of the stateUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateUri(String value) {
        this.stateUri = value;
    }

    /**
     * Gets the value of the placesIdPath property.
     * 
     * @return
     *     possible object is
     *     {@link PlacesIdPath }
     *     
     */
    public PlacesIdPath getPlacesIdPath() {
        return placesIdPath;
    }

    /**
     * Sets the value of the placesIdPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlacesIdPath }
     *     
     */
    public void setPlacesIdPath(PlacesIdPath value) {
        this.placesIdPath = value;
    }

}
