//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.16 at 07:08:00 PM CET 
//


package it.polito.dp2.RNS.sol3.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.RNS.sol3.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.RNS.sol3.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RoadsResponse }
     * 
     */
    public RoadsResponse createRoadsResponse() {
        return new RoadsResponse();
    }

    /**
     * Create an instance of {@link VehiclesResponse }
     * 
     */
    public VehiclesResponse createVehiclesResponse() {
        return new VehiclesResponse();
    }

    /**
     * Create an instance of {@link PlacesResponse }
     * 
     */
    public PlacesResponse createPlacesResponse() {
        return new PlacesResponse();
    }

    /**
     * Create an instance of {@link ConnectionsResponse }
     * 
     */
    public ConnectionsResponse createConnectionsResponse() {
        return new ConnectionsResponse();
    }

    /**
     * Create an instance of {@link ParkingArea }
     * 
     */
    public ParkingArea createParkingArea() {
        return new ParkingArea();
    }

    /**
     * Create an instance of {@link RnsRootResponse }
     * 
     */
    public RnsRootResponse createRnsRootResponse() {
        return new RnsRootResponse();
    }

    /**
     * Create an instance of {@link AddVehicleResponse }
     * 
     */
    public AddVehicleResponse createAddVehicleResponse() {
        return new AddVehicleResponse();
    }

    /**
     * Create an instance of {@link PlacesIdPath }
     * 
     */
    public PlacesIdPath createPlacesIdPath() {
        return new PlacesIdPath();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link UriPath }
     * 
     */
    public UriPath createUriPath() {
        return new UriPath();
    }

    /**
     * Create an instance of {@link RoadsResponse.Roads }
     * 
     */
    public RoadsResponse.Roads createRoadsResponseRoads() {
        return new RoadsResponse.Roads();
    }

    /**
     * Create an instance of {@link VehiclesResponse.Vehicles }
     * 
     */
    public VehiclesResponse.Vehicles createVehiclesResponseVehicles() {
        return new VehiclesResponse.Vehicles();
    }

    /**
     * Create an instance of {@link Road }
     * 
     */
    public Road createRoad() {
        return new Road();
    }

    /**
     * Create an instance of {@link PlacesResponse.Places }
     * 
     */
    public PlacesResponse.Places createPlacesResponsePlaces() {
        return new PlacesResponse.Places();
    }

    /**
     * Create an instance of {@link ErrorBody }
     * 
     */
    public ErrorBody createErrorBody() {
        return new ErrorBody();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link NewVehicle }
     * 
     */
    public NewVehicle createNewVehicle() {
        return new NewVehicle();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link RoadSegment }
     * 
     */
    public RoadSegment createRoadSegment() {
        return new RoadSegment();
    }

    /**
     * Create an instance of {@link Gate }
     * 
     */
    public Gate createGate() {
        return new Gate();
    }

    /**
     * Create an instance of {@link UriOfNextPlaces }
     * 
     */
    public UriOfNextPlaces createUriOfNextPlaces() {
        return new UriOfNextPlaces();
    }

    /**
     * Create an instance of {@link ChangeStateRequest }
     * 
     */
    public ChangeStateRequest createChangeStateRequest() {
        return new ChangeStateRequest();
    }

    /**
     * Create an instance of {@link PlacePath }
     * 
     */
    public PlacePath createPlacePath() {
        return new PlacePath();
    }

    /**
     * Create an instance of {@link ConnectionsResponse.Connections }
     * 
     */
    public ConnectionsResponse.Connections createConnectionsResponseConnections() {
        return new ConnectionsResponse.Connections();
    }

    /**
     * Create an instance of {@link MoveRequest }
     * 
     */
    public MoveRequest createMoveRequest() {
        return new MoveRequest();
    }

    /**
     * Create an instance of {@link ParkingArea.ServicesId }
     * 
     */
    public ParkingArea.ServicesId createParkingAreaServicesId() {
        return new ParkingArea.ServicesId();
    }

}
