//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.16 at 07:08:00 PM CET 
//


package it.polito.dp2.RNS.sol3.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="self" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="entryTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="type" type="{}VehicleType"/>
 *         &lt;element name="state" type="{}VehicleState"/>
 *         &lt;element name="positionUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="originUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="destinationUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="placePathUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element ref="{}uriPath"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{}PlateId" />
 *       &lt;attribute name="lastModifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "self",
    "entryTime",
    "type",
    "state",
    "positionUri",
    "originUri",
    "destinationUri",
    "placePathUri",
    "uriPath"
})
@XmlRootElement(name = "vehicle")
public class Vehicle {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String self;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar entryTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected VehicleType type;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected VehicleState state;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String positionUri;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String originUri;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String destinationUri;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String placePathUri;
    @XmlElement(required = true)
    protected UriPath uriPath;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "lastModifiedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedDate;

    /**
     * Gets the value of the self property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelf() {
        return self;
    }

    /**
     * Sets the value of the self property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelf(String value) {
        this.self = value;
    }

    /**
     * Gets the value of the entryTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEntryTime() {
        return entryTime;
    }

    /**
     * Sets the value of the entryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntryTime(XMLGregorianCalendar value) {
        this.entryTime = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleType }
     *     
     */
    public VehicleType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleType }
     *     
     */
    public void setType(VehicleType value) {
        this.type = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleState }
     *     
     */
    public VehicleState getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleState }
     *     
     */
    public void setState(VehicleState value) {
        this.state = value;
    }

    /**
     * Gets the value of the positionUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionUri() {
        return positionUri;
    }

    /**
     * Sets the value of the positionUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionUri(String value) {
        this.positionUri = value;
    }

    /**
     * Gets the value of the originUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginUri() {
        return originUri;
    }

    /**
     * Sets the value of the originUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginUri(String value) {
        this.originUri = value;
    }

    /**
     * Gets the value of the destinationUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationUri() {
        return destinationUri;
    }

    /**
     * Sets the value of the destinationUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationUri(String value) {
        this.destinationUri = value;
    }

    /**
     * Gets the value of the placePathUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlacePathUri() {
        return placePathUri;
    }

    /**
     * Sets the value of the placePathUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlacePathUri(String value) {
        this.placePathUri = value;
    }

    /**
     * Gets the value of the uriPath property.
     * 
     * @return
     *     possible object is
     *     {@link UriPath }
     *     
     */
    public UriPath getUriPath() {
        return uriPath;
    }

    /**
     * Sets the value of the uriPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link UriPath }
     *     
     */
    public void setUriPath(UriPath value) {
        this.uriPath = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedDate(XMLGregorianCalendar value) {
        this.lastModifiedDate = value;
    }

}
