//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.16 at 07:07:59 PM CET 
//


package it.polito.dp2.RNS.sol2.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.RNS.sol2.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.RNS.sol2.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShortestPathRequest }
     * 
     */
    public ShortestPathRequest createShortestPathRequest() {
        return new ShortestPathRequest();
    }

    /**
     * Create an instance of {@link ShortestPathRequest.Relationships }
     * 
     */
    public ShortestPathRequest.Relationships createShortestPathRequestRelationships() {
        return new ShortestPathRequest.Relationships();
    }

    /**
     * Create an instance of {@link Path }
     * 
     */
    public Path createPath() {
        return new Path();
    }

    /**
     * Create an instance of {@link ServiceRootResponse }
     * 
     */
    public ServiceRootResponse createServiceRootResponse() {
        return new ServiceRootResponse();
    }

    /**
     * Create an instance of {@link PostNodeResponse }
     * 
     */
    public PostNodeResponse createPostNodeResponse() {
        return new PostNodeResponse();
    }

    /**
     * Create an instance of {@link PostRelationshipRequest }
     * 
     */
    public PostRelationshipRequest createPostRelationshipRequest() {
        return new PostRelationshipRequest();
    }

    /**
     * Create an instance of {@link PostRelationshipResponse }
     * 
     */
    public PostRelationshipResponse createPostRelationshipResponse() {
        return new PostRelationshipResponse();
    }

    /**
     * Create an instance of {@link PostNodeRequest }
     * 
     */
    public PostNodeRequest createPostNodeRequest() {
        return new PostNodeRequest();
    }

}
