//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.16 at 07:07:59 PM CET 
//


package it.polito.dp2.RNS.sol2.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="node" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="node_index" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="relationship_index" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "node",
    "nodeIndex",
    "relationshipIndex"
})
@XmlRootElement(name = "serviceRootResponse")
public class ServiceRootResponse {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String node;
    @XmlElement(name = "node_index", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String nodeIndex;
    @XmlElement(name = "relationship_index", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String relationshipIndex;

    /**
     * Gets the value of the node property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode() {
        return node;
    }

    /**
     * Sets the value of the node property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode(String value) {
        this.node = value;
    }

    /**
     * Gets the value of the nodeIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeIndex() {
        return nodeIndex;
    }

    /**
     * Sets the value of the nodeIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeIndex(String value) {
        this.nodeIndex = value;
    }

    /**
     * Gets the value of the relationshipIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationshipIndex() {
        return relationshipIndex;
    }

    /**
     * Sets the value of the relationshipIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationshipIndex(String value) {
        this.relationshipIndex = value;
    }

}
